#! /bin/sh
# /etc/init.d/sbc
 
### BEGIN INIT INFO
# Provides:          sbc
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script de inicio sbc
# Description:       Script de inicio sbc
### END INIT INFO
 
 
# Dependiendo de los parámetros que se le pasen al programa se usa una opción u otra
case "$1" in
  start)
    echo "Starting sbc"
    cd /home/pi/SBCServer; /usr/bin/python3 /home/pi/SBCServer/sbc.py &
    ;;
  stop)
    echo "Stopping sbc"
    
    ;;
  *)
    echo "Modo de uso: /etc/init.d/sbc {start|stop}"
    exit 1
    ;;
esac
 
exit 0 
